[package]
name = "porigon-engine"
version = "0.1.0"
authors = ["Maurus Cuelenaere <mcuelenaere@gmail.com>"]
edition = "2018"

[lib]
name = "porigon"

[dependencies]
fst = { version = "0.4.0", default-features = false }
levenshtein_automata = "0.1.1"
itertools = "0.9.0"
serde = { version = "1.0", features = ["derive"] }